language: go

go:
  - 1.3
  - 1.4
  - tip

matrix:
  allow_failures:
    go: tip

install:
  - sudo apt-get install -qq bzr mercurial git
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u golang.org/x/tools/cmd/vet
  - go get -u github.com/mattn/goveralls
  - go get -d ./...

script:
  - go vet ./...
  - go test -v -race ./...
  - go test -v -bench ./...
  - ./test-coverage.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/49a2d891625bbabb7d55
    on_success: change
    on_failure: always
    on_start: false
